# Generated by Django 4.2.1 on 2023-08-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='selected',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
