# Generated by Django 4.2.1 on 2023-08-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_questions_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='selected',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='selected',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
