# Generated by Django 4.2.1 on 2023-08-02 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_quiz_number_of_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answers',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
