# Generated by Django 4.2.1 on 2023-08-14 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_useranswer_selected_quiz_timelimit_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.quiz'),
            preserve_default=False,
        ),
    ]
