# Generated by Django 4.2.1 on 2023-08-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_results_totalmarks_alter_results_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='Attempted',
            field=models.BooleanField(default=False),
        ),
    ]
