# Generated by Django 4.2.1 on 2023-08-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_credits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='name',
        ),
    ]
